### ISSUE TITLE
dfdl:nilKind and dfdl:nilValue on simple types

### ISSUE THREAD

**Issue by smhdfdl** [DFDLSchemas/NITF#2]
Eg simple type `BCS-A` and `ECS-A`.

The spec does not allow DFDL nil properties on simple types.

**Comment by mbeckerle** [comment]
There's a bug in Daffodil. It is not enforcing this constraint.

https://opensource.ncsa.illinois.edu/jira/browse/DFDL-1763

That doesn't stop fixing this schema tho.
